# HSK 1급 기반 30일 커리큘럼
# 매일 단어 3개 + 예문 + 문법 포인트

CURRICULUM = [
    {
        "day": 1, "topic": "인사",
        "words": [
            {"zh": "你好",   "pinyin": "nǐ hǎo",   "kr": "안녕하세요"},
            {"zh": "谢谢",   "pinyin": "xiè xiè",   "kr": "감사합니다"},
            {"zh": "再见",   "pinyin": "zài jiàn",  "kr": "안녕히 가세요"},
        ],
        "example": ("你好！谢谢你。再见！",
                    "nǐ hǎo！xiè xiè nǐ。zài jiàn！",
                    "안녕하세요! 감사합니다. 안녕히 가세요!"),
        "grammar": ("你好 = 你(너) + 好(좋다) → 상대를 향한 인사",
                    "你好，我叫小明。",
                    "nǐ hǎo，wǒ jiào xiǎo míng。",
                    "안녕하세요, 저는 샤오밍이에요."),
    },
    {
        "day": 2, "topic": "기본 표현",
        "words": [
            {"zh": "对不起", "pinyin": "duì bu qǐ",  "kr": "죄송합니다"},
            {"zh": "没关系", "pinyin": "méi guān xi", "kr": "괜찮아요"},
            {"zh": "请",     "pinyin": "qǐng",        "kr": "부탁합니다 / 어서"},
        ],
        "example": ("对不起！没关系。",
                    "duì bu qǐ！méi guān xi。",
                    "죄송합니다! 괜찮아요."),
        "grammar": ("请 + 동사 = 정중한 부탁",
                    "请坐。",
                    "qǐng zuò。",
                    "앉으세요."),
    },
    {
        "day": 3, "topic": "나 · 너 · 그",
        "words": [
            {"zh": "我",  "pinyin": "wǒ",  "kr": "나 / 저"},
            {"zh": "你",  "pinyin": "nǐ",  "kr": "너 / 당신"},
            {"zh": "他",  "pinyin": "tā",  "kr": "그 / 그녀(她)"},
        ],
        "example": ("我是学生，你呢？",
                    "wǒ shì xuéshēng，nǐ ne？",
                    "저는 학생이에요, 당신은요?"),
        "grammar": ("주어 + 是 + 명사 = ~이에요",
                    "他是老师。",
                    "tā shì lǎoshī。",
                    "그는 선생님이에요."),
    },
    {
        "day": 4, "topic": "우리 · 이것 · 저것",
        "words": [
            {"zh": "我们", "pinyin": "wǒ men", "kr": "우리"},
            {"zh": "这",   "pinyin": "zhè",    "kr": "이것 / 이"},
            {"zh": "那",   "pinyin": "nà",     "kr": "저것 / 저"},
        ],
        "example": ("这是我们的学校。",
                    "zhè shì wǒ men de xuéxiào。",
                    "이것은 우리 학교예요."),
        "grammar": ("这/那 + 是 + 명사 = 이것/저것은 ~이에요",
                    "那是什么？",
                    "nà shì shénme？",
                    "저것은 무엇인가요?"),
    },
    {
        "day": 5, "topic": "숫자 1~5",
        "words": [
            {"zh": "一二三", "pinyin": "yī èr sān", "kr": "1 · 2 · 3"},
            {"zh": "四",     "pinyin": "sì",         "kr": "4"},
            {"zh": "五",     "pinyin": "wǔ",         "kr": "5"},
        ],
        "example": ("我有三个苹果。",
                    "wǒ yǒu sān gè píngguǒ。",
                    "저는 사과가 세 개 있어요."),
        "grammar": ("숫자 + 个(gè) + 명사 = ~개의 ~",
                    "两个人。",
                    "liǎng gè rén。",
                    "두 사람. (2는 两 liǎng 사용)"),
    },
    {
        "day": 6, "topic": "숫자 6~10",
        "words": [
            {"zh": "六七八", "pinyin": "liù qī bā",  "kr": "6 · 7 · 8"},
            {"zh": "九",     "pinyin": "jiǔ",         "kr": "9"},
            {"zh": "十",     "pinyin": "shí",         "kr": "10"},
        ],
        "example": ("今天是八月七日。",
                    "jīntiān shì bā yuè qī rì。",
                    "오늘은 8월 7일이에요."),
        "grammar": ("십 단위: 十一(11) 二十(20) 三十(30)",
                    "我今年二十岁。",
                    "wǒ jīnnián èrshí suì。",
                    "저는 올해 스무 살이에요."),
    },
    {
        "day": 7, "topic": "날짜와 시간",
        "words": [
            {"zh": "今天",   "pinyin": "jīntiān",  "kr": "오늘"},
            {"zh": "明天",   "pinyin": "míngtiān", "kr": "내일"},
            {"zh": "昨天",   "pinyin": "zuótiān",  "kr": "어제"},
        ],
        "example": ("今天天气很好。",
                    "jīntiān tiānqì hěn hǎo。",
                    "오늘 날씨가 매우 좋아요."),
        "grammar": ("很(hěn) + 형용사 = 매우 ~하다",
                    "昨天很冷，今天很热。",
                    "zuótiān hěn lěng，jīntiān hěn rè。",
                    "어제는 매우 추웠고, 오늘은 매우 더워요."),
    },
    {
        "day": 8, "topic": "지금 몇 시?",
        "words": [
            {"zh": "现在",   "pinyin": "xiànzài",  "kr": "지금"},
            {"zh": "点",     "pinyin": "diǎn",     "kr": "시 (시각 단위)"},
            {"zh": "分钟",   "pinyin": "fēnzhōng", "kr": "분"},
        ],
        "example": ("现在几点？现在三点半。",
                    "xiànzài jǐ diǎn？xiànzài sān diǎn bàn。",
                    "지금 몇 시예요? 지금 3시 반이에요."),
        "grammar": ("几点(jǐ diǎn) = 몇 시   半(bàn) = 30분",
                    "我八点去学校。",
                    "wǒ bā diǎn qù xuéxiào。",
                    "저는 8시에 학교에 가요."),
    },
    {
        "day": 9, "topic": "요일",
        "words": [
            {"zh": "星期一", "pinyin": "xīngqī yī",  "kr": "월요일"},
            {"zh": "星期三", "pinyin": "xīngqī sān", "kr": "수요일"},
            {"zh": "星期天", "pinyin": "xīngqī tiān","kr": "일요일"},
        ],
        "example": ("今天星期几？今天星期三。",
                    "jīntiān xīngqī jǐ？jīntiān xīngqī sān。",
                    "오늘 무슨 요일이에요? 오늘 수요일이에요."),
        "grammar": ("星期(xīngqī) + 숫자 = 요일  (일요일만 天/日)",
                    "星期天我在家休息。",
                    "xīngqī tiān wǒ zài jiā xiūxi。",
                    "일요일에 저는 집에서 쉬어요."),
    },
    {
        "day": 10, "topic": "가족 1",
        "words": [
            {"zh": "爸爸",   "pinyin": "bàba",   "kr": "아빠"},
            {"zh": "妈妈",   "pinyin": "māma",   "kr": "엄마"},
            {"zh": "哥哥",   "pinyin": "gēge",   "kr": "오빠 / 형"},
        ],
        "example": ("我爸爸是医生，妈妈是老师。",
                    "wǒ bàba shì yīshēng，māma shì lǎoshī。",
                    "우리 아빠는 의사이고, 엄마는 선생님이에요."),
        "grammar": ("我的(wǒ de) = 나의  →  내 가족 소개",
                    "这是我的家人。",
                    "zhè shì wǒ de jiārén。",
                    "이분들이 제 가족이에요."),
    },
    {
        "day": 11, "topic": "가족 2",
        "words": [
            {"zh": "姐姐",   "pinyin": "jiějie",  "kr": "언니 / 누나"},
            {"zh": "弟弟",   "pinyin": "dìdi",    "kr": "남동생"},
            {"zh": "妹妹",   "pinyin": "mèimei",  "kr": "여동생"},
        ],
        "example": ("我有一个妹妹和一个弟弟。",
                    "wǒ yǒu yī gè mèimei hé yī gè dìdi。",
                    "저는 여동생 한 명과 남동생 한 명이 있어요."),
        "grammar": ("有(yǒu) = 있다  和(hé) = 그리고 / ~와",
                    "你有兄弟姐妹吗？",
                    "nǐ yǒu xiōngdì jiěmèi ma？",
                    "형제자매가 있나요?"),
    },
    {
        "day": 12, "topic": "음식",
        "words": [
            {"zh": "饭",    "pinyin": "fàn",       "kr": "밥 / 식사"},
            {"zh": "面条",  "pinyin": "miàntiáo",  "kr": "면 / 국수"},
            {"zh": "饺子",  "pinyin": "jiǎozi",    "kr": "만두"},
        ],
        "example": ("我想吃饺子。",
                    "wǒ xiǎng chī jiǎozi。",
                    "저는 만두가 먹고 싶어요."),
        "grammar": ("想(xiǎng) + 동사 = ~하고 싶다",
                    "你想吃什么？",
                    "nǐ xiǎng chī shénme？",
                    "무엇을 먹고 싶으세요?"),
    },
    {
        "day": 13, "topic": "과일",
        "words": [
            {"zh": "苹果",  "pinyin": "píngguǒ", "kr": "사과"},
            {"zh": "香蕉",  "pinyin": "xiāngjiāo","kr": "바나나"},
            {"zh": "西瓜",  "pinyin": "xīguā",   "kr": "수박"},
        ],
        "example": ("我喜欢吃苹果和西瓜。",
                    "wǒ xǐhuān chī píngguǒ hé xīguā。",
                    "저는 사과와 수박을 좋아해요."),
        "grammar": ("喜欢(xǐhuān) + 동사/명사 = ~을 좋아하다",
                    "你喜欢什么水果？",
                    "nǐ xǐhuān shénme shuǐguǒ？",
                    "어떤 과일을 좋아하세요?"),
    },
    {
        "day": 14, "topic": "음료",
        "words": [
            {"zh": "水",    "pinyin": "shuǐ",    "kr": "물"},
            {"zh": "茶",    "pinyin": "chá",     "kr": "차"},
            {"zh": "咖啡",  "pinyin": "kāfēi",   "kr": "커피"},
        ],
        "example": ("请给我一杯水。",
                    "qǐng gěi wǒ yī bēi shuǐ。",
                    "물 한 잔 주세요."),
        "grammar": ("一杯(yī bēi) = 한 잔  给(gěi) = 주다",
                    "你喝茶还是咖啡？",
                    "nǐ hē chá háishì kāfēi？",
                    "차를 마실까요, 아니면 커피를 마실까요?"),
    },
    {
        "day": 15, "topic": "장소",
        "words": [
            {"zh": "学校",  "pinyin": "xuéxiào", "kr": "학교"},
            {"zh": "医院",  "pinyin": "yīyuàn",  "kr": "병원"},
            {"zh": "商店",  "pinyin": "shāngdiàn","kr": "상점 / 가게"},
        ],
        "example": ("学校在医院旁边。",
                    "xuéxiào zài yīyuàn pángbiān。",
                    "학교는 병원 옆에 있어요."),
        "grammar": ("在(zài) + 장소 = ~에 있다",
                    "你在哪里？",
                    "nǐ zài nǎlǐ？",
                    "어디에 있어요?"),
    },
    {
        "day": 16, "topic": "집과 직장",
        "words": [
            {"zh": "家",    "pinyin": "jiā",     "kr": "집"},
            {"zh": "公司",  "pinyin": "gōngsī",  "kr": "회사"},
            {"zh": "银行",  "pinyin": "yínháng", "kr": "은행"},
        ],
        "example": ("我家在公司附近。",
                    "wǒ jiā zài gōngsī fùjìn。",
                    "우리 집은 회사 근처에 있어요."),
        "grammar": ("附近(fùjìn) = 근처  离(lí) = ~에서 (거리)",
                    "银行离这里很近。",
                    "yínháng lí zhèlǐ hěn jìn。",
                    "은행은 여기서 매우 가까워요."),
    },
    {
        "day": 17, "topic": "교통",
        "words": [
            {"zh": "公共汽车","pinyin": "gōnggòng qìchē","kr": "버스"},
            {"zh": "地铁",   "pinyin": "dìtiě",          "kr": "지하철"},
            {"zh": "出租车", "pinyin": "chūzūchē",        "kr": "택시"},
        ],
        "example": ("我坐地铁去学校。",
                    "wǒ zuò dìtiě qù xuéxiào。",
                    "저는 지하철을 타고 학교에 가요."),
        "grammar": ("坐(zuò) + 교통수단 + 去 + 장소 = ~을 타고 ~에 가다",
                    "你怎么去公司？",
                    "nǐ zěnme qù gōngsī？",
                    "회사에 어떻게 가요?"),
    },
    {
        "day": 18, "topic": "쇼핑",
        "words": [
            {"zh": "买",    "pinyin": "mǎi",        "kr": "사다"},
            {"zh": "多少钱","pinyin": "duōshǎo qián","kr": "얼마예요?"},
            {"zh": "贵",    "pinyin": "guì",         "kr": "비싸다"},
        ],
        "example": ("这个多少钱？太贵了！",
                    "zhège duōshǎo qián？tài guì le！",
                    "이것은 얼마예요? 너무 비싸요!"),
        "grammar": ("太(tài) + 형용사 + 了 = 너무 ~하다",
                    "便宜一点可以吗？",
                    "piányí yīdiǎn kěyǐ ma？",
                    "조금 깎아줄 수 있나요?"),
    },
    {
        "day": 19, "topic": "색깔",
        "words": [
            {"zh": "红色",  "pinyin": "hóngsè", "kr": "빨간색"},
            {"zh": "蓝色",  "pinyin": "lánsè",  "kr": "파란색"},
            {"zh": "白色",  "pinyin": "báisè",  "kr": "흰색"},
        ],
        "example": ("我喜欢红色和蓝色。",
                    "wǒ xǐhuān hóngsè hé lánsè。",
                    "저는 빨간색과 파란색을 좋아해요."),
        "grammar": ("颜色(yánsè) = 색깔  什么颜色 = 무슨 색",
                    "你喜欢什么颜色？",
                    "nǐ xǐhuān shénme yánsè？",
                    "무슨 색을 좋아하세요?"),
    },
    {
        "day": 20, "topic": "크기와 양",
        "words": [
            {"zh": "大",  "pinyin": "dà",   "kr": "크다"},
            {"zh": "小",  "pinyin": "xiǎo", "kr": "작다"},
            {"zh": "多",  "pinyin": "duō",  "kr": "많다"},
        ],
        "example": ("这件衣服太大了，有小一点的吗？",
                    "zhè jiàn yīfu tài dà le，yǒu xiǎo yīdiǎn de ma？",
                    "이 옷이 너무 커요, 조금 작은 것이 있나요?"),
        "grammar": ("一点(yīdiǎn) = 조금   有没有 = 있나요?",
                    "请给我多一点。",
                    "qǐng gěi wǒ duō yīdiǎn。",
                    "조금 더 주세요."),
    },
    {
        "day": 21, "topic": "기본 동사: 있다·없다·이다",
        "words": [
            {"zh": "是",  "pinyin": "shì",  "kr": "~이다"},
            {"zh": "有",  "pinyin": "yǒu",  "kr": "있다 / 가지다"},
            {"zh": "没有","pinyin": "méiyǒu","kr": "없다 / 안 가지다"},
        ],
        "example": ("我有手机，但是没有电脑。",
                    "wǒ yǒu shǒujī，dànshì méiyǒu diànnǎo。",
                    "저는 핸드폰이 있지만 컴퓨터는 없어요."),
        "grammar": ("不是(bú shì) = ~이 아니다  没有 = 없다(부정)",
                    "我不是老师，我是学生。",
                    "wǒ bú shì lǎoshī，wǒ shì xuéshēng。",
                    "저는 선생님이 아니에요, 저는 학생이에요."),
    },
    {
        "day": 22, "topic": "이동 동사",
        "words": [
            {"zh": "去",  "pinyin": "qù",  "kr": "가다"},
            {"zh": "来",  "pinyin": "lái", "kr": "오다"},
            {"zh": "回",  "pinyin": "huí", "kr": "돌아가다/오다"},
        ],
        "example": ("我去图书馆，你来吗？",
                    "wǒ qù túshūguǎn，nǐ lái ma？",
                    "저는 도서관에 가요, 당신도 올 건가요?"),
        "grammar": ("吗(ma) = 문장 끝에 붙여 의문문 만들기",
                    "你什么时候回家？",
                    "nǐ shénme shíhòu huí jiā？",
                    "언제 집에 돌아가요?"),
    },
    {
        "day": 23, "topic": "먹고 마시고 자다",
        "words": [
            {"zh": "吃",  "pinyin": "chī",   "kr": "먹다"},
            {"zh": "喝",  "pinyin": "hē",    "kr": "마시다"},
            {"zh": "睡觉","pinyin": "shuìjiào","kr": "자다"},
        ],
        "example": ("我每天七点吃早饭。",
                    "wǒ měitiān qī diǎn chī zǎofàn。",
                    "저는 매일 7시에 아침을 먹어요."),
        "grammar": ("每天(měitiān) = 매일  早/午/晚饭 = 아침/점심/저녁",
                    "你几点睡觉？",
                    "nǐ jǐ diǎn shuìjiào？",
                    "몇 시에 자요?"),
    },
    {
        "day": 24, "topic": "좋다 · 크다 · 빠르다",
        "words": [
            {"zh": "好",  "pinyin": "hǎo",  "kr": "좋다"},
            {"zh": "快",  "pinyin": "kuài", "kr": "빠르다"},
            {"zh": "慢",  "pinyin": "màn",  "kr": "느리다"},
        ],
        "example": ("请快一点！不要太慢。",
                    "qǐng kuài yīdiǎn！bú yào tài màn。",
                    "빨리 해주세요! 너무 느리면 안 돼요."),
        "grammar": ("不要(bú yào) + 동사 = ~하지 마세요",
                    "不要说话。",
                    "bú yào shuōhuà。",
                    "말하지 마세요."),
    },
    {
        "day": 25, "topic": "날씨",
        "words": [
            {"zh": "天气",  "pinyin": "tiānqì", "kr": "날씨"},
            {"zh": "下雨",  "pinyin": "xià yǔ", "kr": "비가 오다"},
            {"zh": "下雪",  "pinyin": "xià xuě","kr": "눈이 오다"},
        ],
        "example": ("今天天气怎么样？今天下雨。",
                    "jīntiān tiānqì zěnmeyàng？jīntiān xià yǔ。",
                    "오늘 날씨가 어때요? 오늘 비가 와요."),
        "grammar": ("怎么样(zěnmeyàng) = 어때요? (상태 질문)",
                    "明天天气怎么样？",
                    "míngtiān tiānqì zěnmeyàng？",
                    "내일 날씨가 어떨까요?"),
    },
    {
        "day": 26, "topic": "몸과 건강",
        "words": [
            {"zh": "头",   "pinyin": "tóu",     "kr": "머리"},
            {"zh": "不舒服","pinyin": "bù shūfu", "kr": "불편하다 / 몸이 안 좋다"},
            {"zh": "医生",  "pinyin": "yīshēng", "kr": "의사"},
        ],
        "example": ("我头不舒服，要去看医生。",
                    "wǒ tóu bù shūfu，yào qù kàn yīshēng。",
                    "머리가 안 좋아서 의사를 보러 가야 해요."),
        "grammar": ("要(yào) + 동사 = ~해야 한다 / ~할 것이다",
                    "你要多喝水。",
                    "nǐ yào duō hē shuǐ。",
                    "물을 많이 마셔야 해요."),
    },
    {
        "day": 27, "topic": "위치와 방향",
        "words": [
            {"zh": "上面", "pinyin": "shàngmiàn","kr": "위"},
            {"zh": "下面", "pinyin": "xiàmiàn",  "kr": "아래"},
            {"zh": "旁边", "pinyin": "pángbiān", "kr": "옆"},
        ],
        "example": ("书在桌子上面，包在椅子旁边。",
                    "shū zài zhuōzi shàngmiàn，bāo zài yǐzi pángbiān。",
                    "책은 책상 위에 있고, 가방은 의자 옆에 있어요."),
        "grammar": ("在 + 위치 = ~에 있다  前/后 = 앞/뒤",
                    "银行在学校前面。",
                    "yínháng zài xuéxiào qiánmiàn。",
                    "은행은 학교 앞에 있어요."),
    },
    {
        "day": 28, "topic": "감정 표현",
        "words": [
            {"zh": "高兴", "pinyin": "gāoxìng", "kr": "기쁘다 / 즐겁다"},
            {"zh": "难过", "pinyin": "nánguò",  "kr": "슬프다"},
            {"zh": "累",   "pinyin": "lèi",     "kr": "피곤하다"},
        ],
        "example": ("今天很高兴认识你！",
                    "jīntiān hěn gāoxìng rènshi nǐ！",
                    "오늘 만나서 정말 반가워요!"),
        "grammar": ("认识(rènshi) = 알다 / 알게 되다",
                    "你看起来很累。",
                    "nǐ kàn qǐlái hěn lèi。",
                    "피곤해 보여요."),
    },
    {
        "day": 29, "topic": "할 수 있다 · 원하다",
        "words": [
            {"zh": "可以", "pinyin": "kěyǐ",  "kr": "해도 된다 / 할 수 있다"},
            {"zh": "能",   "pinyin": "néng",  "kr": "~할 수 있다 (능력)"},
            {"zh": "想",   "pinyin": "xiǎng", "kr": "~하고 싶다 / 생각하다"},
        ],
        "example": ("我想学中文，你能教我吗？",
                    "wǒ xiǎng xué zhōngwén，nǐ néng jiāo wǒ ma？",
                    "저는 중국어를 배우고 싶은데, 가르쳐 줄 수 있어요?"),
        "grammar": ("可以 vs 能: 可以=허락, 能=능력",
                    "这里可以拍照吗？",
                    "zhèlǐ kěyǐ pāizhào ma？",
                    "여기서 사진을 찍어도 되나요?"),
    },
    {
        "day": 30, "topic": "종합 복습",
        "words": [
            {"zh": "学习", "pinyin": "xuéxí",   "kr": "공부하다"},
            {"zh": "努力", "pinyin": "nǔlì",    "kr": "노력하다"},
            {"zh": "加油", "pinyin": "jiā yóu", "kr": "힘내요! / 파이팅!"},
        ],
        "example": ("每天努力学习，你一定能成功！",
                    "měitiān nǔlì xuéxí，nǐ yīdìng néng chénggōng！",
                    "매일 열심히 공부하면 반드시 성공할 수 있어요!"),
        "grammar": ("一定(yīdìng) = 반드시  恭喜你完成30天！",
                    "你的中文越来越好！",
                    "nǐ de zhōngwén yuèláiyuè hǎo！",
                    "당신의 중국어가 갈수록 좋아지고 있어요!"),
    },
]
